label_mapping = {0: "Low", 1: "Moderate", 2: "High"}

expected_columns = [
    "Age",
    "Gender",
    "BMI",
    "Smoking_Status",
    "Alcohol_Consumption",
    "Physical_Activity_Level",
    "Diet_Type",
    "Cholesterol",
    "Glucose_Level",
    "HbA1c",
    "PRS_Cardiometabolic",
    "PRS_Type2Diabetes",
    "APOE_e4_Carrier",
    "BRCA_Pathogenic_Variant",
    "Family_History_CVD",
    "Family_History_T2D",
    "Stress_Level",
    "Depression_Score",
    "Anxiety_Score",
    "Social_Isolation_Index",
    "Sleep_Hours",
    "Sleep_Quality",
    "Resting_Heart_Rate",
    "HRV",
    "Systolic_BP",
    "Diastolic_BP",
    "LDL",
    "HDL",
    "Triglycerides",
    "CRP",
    "eGFR",
    "Waist_Circumference",
]
